### ISSUE TITLE
Calc() inside of @supports broken with minify

### ISSUE THREAD

**Issue by DouglasRiddle** [madskristensen/BundlerMinifier#521]
### Installed product versions
- Visual Studio: 2019 Enterprise
- 2.8.396

### Description
When a CSS ```calc()``` is used within an ```@supports``` section it is broken by ```bundleconfig.json``` minify.

### Steps to recreate
A mostly default MVVM app has been created at https://github.com/DouglasRiddle/MinifyExample with two divs. One with the broken CSS inside of ```@supports``` and one working as expected in the base CSS.

### Current behavior
```CSS
@supports (top: max(0%)) {
    .minify-break {
        /* Expect 16px, get 0 due to leading space being removed from "+" on minify */
        padding: max(16px, calc(var(--mdc-shape-small, 4px) + 4px));
    }
}
```
minfies as
```CSS
@supports (top:max(0%)){.minify-break{padding:max(16px,calc(var(--mdc-shape-small,4px)+ 4px));}}
```

### Expected behavior
```CSS
@supports (top:max(0%)){.minify-break{padding:max(16px,calc(var(--mdc-shape-small,4px) + 4px));}}
```
