### ISSUE TITLE
Support CSS nesting

### ISSUE THREAD

**Issue by json-derulo** [madskristensen/BundlerMinifier#608]
I want to use [CSS nesting](https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector) in my project, however during the bundle / minification, an error is thrown

Example code:

```css
.element {
  background-color: #fff;

  &:hover {
    background-color: #ddd;
  }
}
```

With this code, I'm getting the following error:

```
Error 0: Expected semicolon or closing curly-brace, found '&'
```
